### ISSUE TITLE
the  reop  

### ISSUE THREAD

**Issue by Ssato23** [NickNo-dev/LP-ModManager#11]
the  repo  dosent  work  it  sayes  the half  of the  path doesn't  work

**Comment by NickNo-dev** [comment]
Just checked. Works like expected. Which version of the ModManager are you using, and did you extract it right next to the lifeplay.exe?

**Comment by Ssato23** [comment]
i am  using  the  new  version

**Comment by Ssato23** [comment]
I always  get  the  error  code  for  me  I  am not lying that happen to me  three  times    on  the new  version what  I  am using  the

**Comment by NickNo-dev** [comment]
Ok, please describe what you do exactly. and if possible attach a screenshot of both the main window and the message.

**Comment by Ssato23** [comment]
I have the  pictures  but it's in Hebrew  with English  
![error](https://user-images.githubusercontent.com/23505057/109639918-79754880-7b58-11eb-947f-f80c65f28b92.jpg)

**Comment by Ssato23** [comment]
it  says  that  the  path  he  can't  access  it  or  half  of  it is in  the  one  drive    and  if  its  the  new  version  he  cant  download it

**Comment by Ssato23** [comment]
I put  it  and  click  on  it  and  it  doesn't  work  if  I  say  okay  I  get  it  without  the  repository

**Comment by NickNo-dev** [comment]
Hm, strange.

1. can you access the URL https://raw.githubusercontent.com/NickNo-dev/LP-Mods/master/repo.xml from that machine?
2. does the file "lprepo.xml" exist while this message is displayed? If yes, can you attach it?
3. could you try to put lifeplay+launcher into a folder directly under "C:" eg. "C:\LifePlay"?

**Comment by Ssato23** [comment]
1  I can access  with  the  access the URL  
2. it  exits  and  then  got  delate  
3. 3. I try

**Comment by Ssato23** [comment]
it works only in the  C:/ what  do  I do

**Comment by NickNo-dev** [comment]
onedrive is some sort of virtual/managed folder that might be the reason.
on the other hand I NEVER tried it on a hebrew system ;-)
might be another option. So to find the error you can try some hebrew folder name in C: or just move it out of your one drive.

not sure you want M$ to know all your games either ;)

**Comment by Ssato23** [comment]
okay I try

**Comment by Ssato23** [comment]
i  remove  it  from the one  drive  and  see

**Comment by Ssato23** [comment]
i  remove  it  from the one  drive  and  still  not  work maybe  I will  stay  as  hidden or  I won't use  the LP MODMANGER

**Comment by NickNo-dev** [comment]
Could you give me the path you use as a piece of text that I can copy from here?

**Comment by Ssato23** [comment]
C:\Users\User\OneDrive\שולחן העבודה\Game lunchers and games\‏‏תיקיה חדשה\lifeplay
my computer C:\users\user\onedrive\desktop\game lunchers and games\new folder\life[lay
nut  think its  the  M$ bug  because it's Microsoft
